### ISSUE TITLE
Installed atom-ng via the AUR, having trouble installing plugins via apm, appreciate any help.

### ISSUE THREAD

**Issue by Jieiku** [Alex313031/atom-ng#4]
```bash
paru atom-ng

/opt/atom-ng/resources/app/apm/bin/apm disable metrics exception-reporting

/opt/atom-ng/resources/app/apm/bin/apm install split-diff
```

```
Installing split-diff to /home/jieiku/.atom/packages /opt/atom-ng/resources/app/apm/lib/install.js:256
          if (body.releases.latest) {
                            ^

TypeError: Cannot read property 'latest' of undefined
    at /opt/atom-ng/resources/app/apm/lib/install.js:256:29
    at Request._callback (/opt/atom-ng/resources/app/apm/lib/request.js:57:22)
    at Request.self.callback (/opt/atom-ng/resources/app/apm/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/opt/atom-ng/resources/app/apm/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/opt/atom-ng/resources/app/apm/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
```

```
npm -v
9.7.1

node -v
v16.20.0
```

other plugins I generally use:

```
/opt/atom-ng/resources/app/apm/bin/apm install split-diff
/opt/atom-ng/resources/app/apm/bin/apm install open-recent
/opt/atom-ng/resources/app/apm/bin/apm install sort-lines
/opt/atom-ng/resources/app/apm/bin/apm install minimap
/opt/atom-ng/resources/app/apm/bin/apm install minimap-split-diff
```

EDIT: I found out you can simply install the packages into: ~/.atom/packages my old hard drive had these packages so I just copied them over, will leave this issue open though because I would still like to know how to fix this if possible.

**Comment by Jieiku** [comment]
I just created a high contrast theme based off github-atom-dark-syntax.

https://github.com/Jieiku/github-atom-darker-syntax

**Comment by Alex313031** [comment]
@Jieiku Nice theme. I might add it to the list of included themes in atom-ng.

Also, the reason it fails is that apm in atom-ng still expects atom.io to be up, but all the sites under that were taken down and now redirect to > https://github.blog/2022-06-08-sunsetting-atom/
You can still install packages with apm from git repositories like so 
`apm install thomaslindstrom/color-picker` installs https://github.com/thomaslindstrom/color-picker.git
You can also drag and drop extensions into that dir like you did. This is actually how I integrate the new preinstalled packages that I added: minimap and atom-ng browser. During the first run, it copies and untars two dirs containing those extensions to the user profile folder.

I have looked into possible using Pulsar's fork of apm to enable installing packages again like how it used to work. The problem is I don't have a server with the infrastructure to host or the traffic for all the packages.

For the flight manual, I built it and am serving it on my site here > https://flight-manual-atom-io.github.io/

**Comment by Jieiku** [comment]
Awesome, thanks for the response, your example more than takes care of the problem then, and like I said, I still had a copy of all the packages that I use :)

Feel free to do whatever you want with the theme!

Thanks again.
